# Generated by Django 4.2.24 on 2025-09-26 05:48

from django.db import migrations, models, connection
from django.utils import timezone


def recreate_studentprofile_table(apps, schema_editor):
    """Recreate the StudentProfile table with new fields"""
    # Get the StudentProfile model
    StudentProfile = apps.get_model('accounts', 'StudentProfile')

    # Create new table with all fields including the new ones
    with connection.cursor() as cursor:
        # Drop the existing table
        cursor.execute("DROP TABLE IF EXISTS accounts_studentprofile")

        # Create new table with all fields
        cursor.execute("""
            CREATE TABLE accounts_studentprofile (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                level VARCHAR(20) NOT NULL,
                points INTEGER NOT NULL,
                xp INTEGER NOT NULL,
                total_xp INTEGER NOT NULL,
                streak_correct INTEGER NOT NULL,
                progress INTEGER NOT NULL,
                last_difficulty VARCHAR(20) NOT NULL,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL,
                user_id INTEGER NOT NULL REFERENCES auth_user(id)
            )
        """)

        # Create indexes
        cursor.execute("CREATE INDEX accounts_studentprofile_user_id ON accounts_studentprofile(user_id)")
        cursor.execute("CREATE INDEX accounts_studentprofile_level ON accounts_studentprofile(level)")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(recreate_studentprofile_table),
    ]
