# Generated by Django 4.2.24 on 2025-09-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_total_xp_studentprofile_xp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='total_xp',
            field=models.PositiveIntegerField(default=0, help_text='Total experience points earned'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='xp',
            field=models.PositiveIntegerField(default=0, help_text='Experience points for current level'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', help_text='Current skill level of the student', max_length=20),
        ),
    ]
