# Generated by Django 4.2.24 on 2025-09-26 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QLearningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_hash', models.CharField(help_text='Current state hash', max_length=32)),
                ('action', models.CharField(help_text='Action taken', max_length=20)),
                ('reward', models.FloatField(help_text='Reward received for this action')),
                ('q_value_before', models.FloatField(help_text='Q-value before update')),
                ('q_value_after', models.FloatField(help_text='Q-value after update')),
                ('next_state_hash', models.CharField(blank=True, help_text='Next state hash (for Q-learning update)', max_length=32, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qlearning_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Q-Learning Log',
                'verbose_name_plural': 'Q-Learning Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QTableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_hash', models.CharField(help_text='Hash of the state tuple for efficient lookup', max_length=32)),
                ('action', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], help_text='Action taken in this state', max_length=20)),
                ('q_value', models.FloatField(default=0.0, help_text='Q-value for this state-action pair')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qtable_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Q-Table Entry',
                'verbose_name_plural': 'Q-Table Entries',
                'ordering': ['user', 'state_hash', 'action'],
                'unique_together': {('user', 'state_hash', 'action')},
            },
        ),
    ]
