# Generated by Django 4.2.24 on 2025-09-26 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qlearning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('accuracy_global', 'Global Accuracy'), ('engagement_daily', 'Daily Engagement'), ('hint_distribution', 'Hint Distribution'), ('leaderboard_snapshot', 'Leaderboard Snapshot'), ('qlearning_trend', 'Q-Learning Trend'), ('system_health', 'System Health')], help_text='Type of global metric', max_length=25)),
                ('metric_data', models.JSONField(help_text='The actual metric data')),
                ('time_window', models.CharField(help_text='Time window for this metric (daily, weekly, etc.)', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Global System Log',
                'verbose_name_plural': 'Global System Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserEngagementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('login', 'Login'), ('quiz_attempt', 'Quiz Attempt'), ('level_claim', 'Level Claim'), ('hint_usage', 'Hint Usage'), ('badge_claim', 'Badge Claim'), ('progress_complete', 'Progress Complete')], help_text='Type of engagement event', max_length=20)),
                ('session_id', models.CharField(help_text='Unique session identifier', max_length=64)),
                ('duration_seconds', models.PositiveIntegerField(help_text='Duration of the session in seconds')),
                ('questions_attempted', models.PositiveIntegerField(default=0, help_text='Number of questions attempted in this session')),
                ('hints_used', models.PositiveIntegerField(default=0, help_text='Number of hints used in this session')),
                ('gamification_interactions', models.PositiveIntegerField(default=0, help_text='Number of gamification interactions (badges, levels, etc.)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata for the session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Engagement Log',
                'verbose_name_plural': 'User Engagement Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SuccessRateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(help_text='Question difficulty level', max_length=20)),
                ('total_attempts', models.PositiveIntegerField(help_text='Total number of attempts')),
                ('correct_attempts', models.PositiveIntegerField(help_text='Number of correct attempts')),
                ('average_time_spent', models.FloatField(help_text='Average time spent per question in seconds')),
                ('accuracy_percentage', models.FloatField(help_text='Accuracy percentage (0-100)')),
                ('time_window_start', models.DateTimeField(help_text='Start of the time window for this log')),
                ('time_window_end', models.DateTimeField(help_text='End of the time window for this log')),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Success Rate Log',
                'verbose_name_plural': 'Success Rate Logs',
                'ordering': ['-time_window_end'],
            },
        ),
        migrations.CreateModel(
            name='RewardIncentivesLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('points', 'Points'), ('streak_bonus', 'Streak Bonus'), ('level_up_bonus', 'Level Up Bonus'), ('hidden_reward', 'Hidden Reward'), ('badge', 'Badge'), ('progress_milestone', 'Progress Milestone')], help_text='Type of reward given', max_length=20)),
                ('reward_value', models.FloatField(help_text='Numerical value of the reward')),
                ('trigger_condition', models.JSONField(help_text='What triggered this reward')),
                ('user_reaction', models.JSONField(help_text='User behavior after receiving reward')),
                ('session_continuation', models.BooleanField(help_text='Whether user continued the session after reward')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reward & Incentives Log',
                'verbose_name_plural': 'Reward & Incentives Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ResponseToAdaptationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adaptation_type', models.CharField(choices=[('difficulty_transition', 'Difficulty Transition'), ('hint_adaptation', 'Hint Adaptation'), ('reward_response', 'Reward Response'), ('level_transition', 'Level Transition')], help_text='Type of adaptation', max_length=25)),
                ('old_state', models.JSONField(help_text='State before adaptation')),
                ('new_state', models.JSONField(help_text='State after adaptation')),
                ('adaptation_details', models.JSONField(help_text='Details about the adaptation')),
                ('first_attempt_after', models.JSONField(blank=True, help_text='Result of first attempt after adaptation', null=True)),
                ('hint_usage_change', models.FloatField(default=0.0, help_text='Change in hint usage rate')),
                ('session_duration_change', models.FloatField(default=0.0, help_text='Change in session duration')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Response to Adaptation Log',
                'verbose_name_plural': 'Response to Adaptation Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QLearningPerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_hash', models.CharField(help_text='State hash for this log entry', max_length=32)),
                ('action_distribution', models.JSONField(help_text='Distribution of actions chosen by the agent')),
                ('optimal_action_frequency', models.FloatField(help_text='Frequency of choosing optimal actions (0-1)')),
                ('average_q_value', models.FloatField(help_text='Average Q-value across all states')),
                ('q_table_size', models.PositiveIntegerField(help_text='Number of entries in Q-table')),
                ('learning_progress', models.FloatField(help_text='Learning progress indicator')),
                ('snapshot_interval', models.PositiveIntegerField(help_text='Number of attempts since last snapshot')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional Q-Learning metadata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qlearning_performance_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Q-Learning Performance Log',
                'verbose_name_plural': 'Q-Learning Performance Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LevelTransitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transition_type', models.CharField(choices=[('level_up_manual', 'Manual Level Up'), ('level_down_auto', 'Automatic Level Down'), ('level_reset', 'Level Reset')], help_text='Type of level transition', max_length=20)),
                ('old_level', models.CharField(help_text='Previous level', max_length=20)),
                ('new_level', models.CharField(help_text='New level', max_length=20)),
                ('transition_condition', models.JSONField(help_text='Conditions that triggered the transition')),
                ('performance_metrics', models.JSONField(help_text='Performance metrics at time of transition')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_transition_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Level Transition Log',
                'verbose_name_plural': 'Level Transition Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
