# Generated by Django 4.2.24 on 2025-10-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlearning', '0002_globalsystemlog_userengagementlog_successratelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qlearninglog',
            name='decision_type',
            field=models.CharField(blank=True, help_text='Type of decision (e.g., difficulty_selection, action_update)', max_length=50, null=True),
        ),
    ]
