# Generated by Django 4.2.24 on 2025-10-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qlearning', '0003_qlearninglog_decision_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qlearninglog',
            name='decision_type',
        ),
    ]
