# Generated by Django 4.2.24 on 2025-10-29 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qlearning', '0004_remove_qlearninglog_decision_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_type', models.CharField(choices=[('post_adaptation', 'Post Adaptation Survey'), ('session_end', 'Session End Survey'), ('weekly_feedback', 'Weekly Feedback'), ('difficulty_feedback', 'Difficulty Feedback')], help_text='Type of survey', max_length=20)),
                ('satisfaction_rating', models.IntegerField(choices=[(1, 'Very Dissatisfied'), (2, 'Dissatisfied'), (3, 'Neutral'), (4, 'Satisfied'), (5, 'Very Satisfied')], help_text='Overall satisfaction rating (1-5)')),
                ('difficulty_rating', models.IntegerField(blank=True, help_text='Difficulty appropriateness rating (1-5)', null=True)),
                ('engagement_rating', models.IntegerField(blank=True, help_text='Engagement level rating (1-5)', null=True)),
                ('feedback_text', models.TextField(blank=True, help_text='Open-ended feedback from user')),
                ('would_continue', models.BooleanField(default=True, help_text='Would user continue using the system')),
                ('adaptation_helpful', models.BooleanField(blank=True, help_text='Was the adaptation helpful (for post-adaptation surveys)', null=True)),
                ('context_data', models.JSONField(default=dict, help_text='Context when survey was taken (level, difficulty, etc.)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Survey Response',
                'verbose_name_plural': 'User Survey Responses',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QLearningDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_hash', models.CharField(help_text='Current state hash', max_length=32)),
                ('decision_type', models.CharField(choices=[('exploitation', 'Exploitation (Best Q-value)'), ('exploration', 'Exploration (Random)')], help_text='Was this exploration or exploitation', max_length=15)),
                ('epsilon_value', models.FloatField(help_text='Epsilon value at time of decision')),
                ('action_chosen', models.CharField(help_text='Action that was chosen', max_length=20)),
                ('q_value_chosen', models.FloatField(help_text='Q-value of chosen action')),
                ('best_q_value', models.FloatField(help_text='Best available Q-value')),
                ('all_q_values', models.JSONField(help_text='All Q-values for this state')),
                ('is_optimal', models.BooleanField(help_text='Was the optimal action chosen')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qlearning_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Q-Learning Decision Log',
                'verbose_name_plural': 'Q-Learning Decision Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LoginActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_timestamp', models.DateTimeField(auto_now_add=True)),
                ('logout_timestamp', models.DateTimeField(blank=True, help_text='When user logged out or session ended', null=True)),
                ('session_duration_seconds', models.PositiveIntegerField(blank=True, help_text='Total session duration in seconds', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of login', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser/device information', max_length=255)),
                ('activities_performed', models.JSONField(default=dict, help_text='Activities performed during this session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Activity Log',
                'verbose_name_plural': 'Login Activity Logs',
                'ordering': ['-login_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AdaptationEffectivenessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_rate_before', models.FloatField(help_text='Success rate before adaptation (percentage)')),
                ('avg_time_before', models.FloatField(help_text='Average time per question before adaptation (seconds)')),
                ('attempts_before', models.PositiveIntegerField(help_text='Number of attempts before adaptation')),
                ('success_rate_after', models.FloatField(help_text='Success rate after adaptation (percentage)')),
                ('avg_time_after', models.FloatField(help_text='Average time per question after adaptation (seconds)')),
                ('attempts_after', models.PositiveIntegerField(help_text='Number of attempts after adaptation')),
                ('success_rate_change', models.FloatField(help_text='Change in success rate (percentage points)')),
                ('time_efficiency_change', models.FloatField(help_text='Change in time efficiency (percentage)')),
                ('continued_session', models.BooleanField(help_text='Did user continue session after adaptation')),
                ('attempts_until_quit', models.PositiveIntegerField(blank=True, help_text='Number of attempts before quitting (if applicable)', null=True)),
                ('measurement_window_days', models.PositiveIntegerField(default=7, help_text='Days used for before/after comparison')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('adaptation_event', models.ForeignKey(help_text='The adaptation event being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='effectiveness_logs', to='qlearning.responsetoadaptationlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_effectiveness_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adaptation Effectiveness Log',
                'verbose_name_plural': 'Adaptation Effectiveness Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
