# Generated by Django 4.2.24 on 2025-11-09 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qlearning', '0005_usersurveyresponse_qlearningdecisionlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QLearningState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.CharField(help_text='Unique identifier for the state', max_length=50, unique=True)),
                ('state_type', models.CharField(choices=[('initial', 'Initial State'), ('learning', 'Learning State'), ('mastered', 'Mastered State'), ('struggling', 'Struggling State')], help_text='Type of learning state', max_length=20)),
                ('difficulty', models.CharField(help_text='Difficulty level associated with this state', max_length=20)),
                ('concept', models.CharField(help_text='Learning concept this state represents', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata for the state')),
            ],
        ),
        migrations.CreateModel(
            name='UserLearningState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_values', models.JSONField(default=dict, help_text='Q-values for each possible action in this state')),
                ('visit_count', models.PositiveIntegerField(default=0, help_text='Number of times user has been in this state')),
                ('last_visited', models.DateTimeField(auto_now=True, help_text='When user was last in this state')),
                ('is_current', models.BooleanField(default=False, help_text="Whether this is the user's current state")),
                ('metadata', models.JSONField(default=dict, help_text='Additional learning state metadata')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='qlearning.qlearningstate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_current', '-last_visited'],
                'unique_together': {('user', 'state')},
            },
        ),
    ]
