# Generated by Django 4.2.24 on 2025-11-12 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qlearning', '0006_qlearningstate_userlearningstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Sangat Buruk'), (2, 'Buruk'), (3, 'Netral'), (4, 'Baik'), (5, 'Sangat Baik')], help_text='Rating kepuasan pengguna')),
                ('feedback', models.TextField(blank=True, help_text='Umpan balik tertulis dari pengguna')),
                ('context', models.JSONField(default=dict, help_text='Konteks saat feedback diberikan (level, kesulitan, dll)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_anonymous', models.BooleanField(default=False, help_text='Apakah feedback ini anonim?')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Umpan Balik Pengguna',
                'verbose_name_plural': 'Umpan Balik Pengguna',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QLearningActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('difficulty_up', 'Tingkatkan Kesulitan'), ('difficulty_down', 'Turunkan Kesulitan'), ('hint', 'Berikan Petunjuk'), ('encourage', 'Berikan Dorongan'), ('challenge', 'Tantangan Baru')], help_text='Jenis aksi yang diambil', max_length=20)),
                ('state_before', models.JSONField(help_text='State sebelum aksi diambil')),
                ('state_after', models.JSONField(help_text='State setelah aksi diambil')),
                ('reward', models.FloatField(help_text='Reward yang diterima untuk aksi ini')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict, help_text='Metadata tambahan untuk aksi ini')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qlearning_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Aksi Q-Learning',
                'verbose_name_plural': 'Log Aksi Q-Learning',
                'ordering': ['-timestamp'],
            },
        ),
    ]
