# Generated by Django 4.2.24 on 2025-11-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlearning', '0007_userfeedback_qlearningactionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qlearningactionlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='user',
        ),
        migrations.AddField(
            model_name='qlearninglog',
            name='is_adaptation',
            field=models.BooleanField(default=False, help_text='Whether this log entry is for an adaptation event'),
        ),
        migrations.AddField(
            model_name='qlearninglog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata for this log entry'),
        ),
        migrations.AddIndex(
            model_name='qlearninglog',
            index=models.Index(fields=['user', 'timestamp'], name='qlearning_q_user_id_00bd53_idx'),
        ),
        migrations.AddIndex(
            model_name='qlearninglog',
            index=models.Index(fields=['is_adaptation', 'timestamp'], name='qlearning_q_is_adap_a5b520_idx'),
        ),
        migrations.DeleteModel(
            name='QLearningActionLog',
        ),
        migrations.DeleteModel(
            name='UserFeedback',
        ),
    ]
