# Generated by Django 4.2.24 on 2025-11-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlearning', '0009_qlearninglog_is_adaptation'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='qlearninglog',
            name='qlearning_q_user_id_00bd53_idx',
        ),
        migrations.RemoveIndex(
            model_name='qlearninglog',
            name='qlearning_q_is_adap_a5b520_idx',
        ),
        migrations.AlterField(
            model_name='qlearninglog',
            name='is_adaptation',
            field=models.BooleanField(default=False, help_text='Whether this log entry is for an adaptation event'),
        ),
        migrations.AlterField(
            model_name='qlearninglog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata for the Q-learning update', null=True),
        ),
    ]
