# Generated by Django 4.2.24 on 2025-09-26 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Alter the existing Question table to match new structure
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
        migrations.AddField(
            model_name='question',
            name='format',
            field=models.CharField(
                choices=[('mcq_simple', 'Multiple Choice (Single Answer)'), ('mcq_complex', 'Multiple Choice (Multiple Answers)'), ('short_answer', 'Short Answer')],
                default='mcq_simple',
                help_text='Question format type',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(
                blank=True,
                help_text='JSON options for MCQ questions (e.g., {"A": "Option 1", "B": "Option 2"})',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_key',
            field=models.TextField(
                help_text='Correct answer(s) - JSON for MCQ, text for short answer'
            ),
        ),
        migrations.AddField(
            model_name='question',
            name='curriculum_tag',
            field=models.CharField(
                blank=True,
                help_text='Curriculum topic/category tag',
                max_length=100
            ),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # Remove old fields that are no longer needed
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='points',
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        # Create the new AttemptLog table
        migrations.CreateModel(
            name='AttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_answer', models.TextField(blank=True, help_text="Student's answer (JSON for MCQ, text for short answer)", null=True)),
                ('is_correct', models.BooleanField(default=False, help_text='Whether the answer was correct')),
                ('difficulty_attempted', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], help_text='Difficulty level at time of attempt', max_length=20)),
                ('time_spent', models.FloatField(help_text='Time spent on question in seconds')),
                ('hint_given', models.TextField(blank=True, help_text='Hint provided to student (if any)', null=True)),
                ('reward_numeric', models.IntegerField(default=0, help_text='Numeric reward/penalty given for this attempt')),
                ('qtable_snapshot', models.JSONField(blank=True, help_text='Q-table snapshot at time of attempt for learning analysis', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_logs', to='quizzes.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attempt Log',
                'verbose_name_plural': 'Attempt Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
