# Generated by Django 4.2.24 on 2025-11-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_attemptlog_is_first_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptlog',
            name='is_first_attempt',
            field=models.BooleanField(default=True, help_text='Whether this was the first attempt at this question'),
        ),
    ]
